# Generated by Django 4.0.4 on 2022-04-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_alter_article_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='thumb',
        ),
    ]
